{% set name = "napari-live-recording" %}
{% set version = "0.3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5bc06130032780cec852882d464f301a58d27abb3cc50539e90aa5a1b4a263aa

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
  run:
    - pims
    - microscope
    - napari
    - numpy
    - opencv
    - pyqtgraph
    - pymmcore-plus >=0.6.7
    - pymmcore-widgets
    - python >={{ python_min }},<3.12
    - qtpy
    - superqt
    - tifffile

test:
  imports:
    - napari_live_recording
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt
    - python {{ python_min }}

about:
  home: https://pypi.org/project/napari-live-recording
  summary: A napari plugin for live video recording with a generic camera device.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/jacopoabramo/napari-live-recording

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - jacopoabramo
